apiVersion: v1
kind: PersistentVolume
metadata:
  name: sppidi-pv
  namespace: d-prd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sppidi-storage
  hostPath:
    path: "/mnt/data"
