apiVersion: v1
kind: Service
metadata:
  name: sppidi-relacional-db
  namespace: d-prd
spec:
  selector:
    app: sppidi-relacional-db
  ports:
    - protocol: TCP
      port: 5432     
      targetPort: 5432  
  type: ClusterIP 
